[Fleet] fix bug when VersionSpecificPolicyAssignmentTask picked up more than 10k agents to reassign (#259132)
## Summary

Fix a bug encountered in scale tests where
VersionSpecificPolicyAssignmentTask picked up more than 10k agents to
reassign, the task failed with a `max_result_window` error from ES.

https://buildkite.com/elastic/observability-perf/builds/5651#019d17fe-8419-4f3c-adf2-41683f2af59c
https://platform-logging.kb.us-west2.gcp.elastic-cloud.com/app/r/s/7EfzN

Added a small fix to chunk querying agent ids to 10k batches.
`getAgentsById` is called from the reassign logic.

```
[VersionSpecificPolicyAssignmentTask] Error reassigning agents to b8642a71-93f9-4e22-853d-ebaadbcc7d3a#9.2: ResponseError: search_phase_execution_exception
	Caused by:
		illegal_argument_exception: Result window is too large, from + size must be less than or equal to: [10000] but was [10400]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.
	Root causes:
		illegal_argument_exception: Result window is too large, from + size must be less than or equal to: [10000] but was [10400]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.
```

### Checklist

Check the PR satisfies following conditions. 

Reviewers should verify this PR satisfies this list as well.

- [ ] Any text added follows [EUI's writing
guidelines](https://elastic.github.io/eui/#/guidelines/writing), uses
sentence case text and includes [i18n
support](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)
- [ ]
[Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html)
was added for features that require explanation or tutorials
- [ ] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios
- [ ] If a plugin configuration key changed, check if it needs to be
allowlisted in the cloud and added to the [docker
list](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)
- [ ] This was checked for breaking HTTP API changes, and any breaking
changes have been approved by the breaking-change committee. The
`release_note:breaking` label should be applied in these situations.
- [ ] [Flaky Test
Runner](https://ci-stats.kibana.dev/trigger_flaky_test_runner/1) was
used on any tests changed
- [ ] The PR description includes the appropriate Release Notes section,
and the correct `release_note:*` label is applied per the
[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)
- [ ] Review the [backport
guidelines](https://docs.google.com/document/d/1VyN5k91e5OVumlc0Gb9RPa3h1ewuPE705nRtioPiTvY/edit?usp=sharing)
and apply applicable `backport:*` labels.

### Identify risks

Does this PR introduce any risks? For example, consider risks like hard
to test bugs, performance regression, potential of data loss.

Describe the risk, its severity, and mitigation for each identified
risk. Invite stakeholders and evaluate how to proceed before merging.

- [ ] [See some risk
examples](https://github.com/elastic/kibana/blob/main/RISK_MATRIX.mdx)
- [ ] ...