Fix translation (#259055)
## Summary

Without this the console includes this error

```
Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "core.kibanaConnectorSpecs.microsoftTeams.auth.oauth.tokenUrl.helpText", rendering default message verbatim
MessageID: core.kibanaConnectorSpecs.microsoftTeams.auth.oauth.tokenUrl.helpText
Default Message: Replace {tenant-id} with your Azure AD tenant ID. For example: https://login.microsoftonline.com/your-tenant-id/oauth2/v2.0/token
Description: undefined
Locale: en
```

> In `@formatjs/intl`, curly braces {...} in a defaultMessage are
treated as ICU message format placeholders, so they require a
corresponding value to be passed in. Our string contains {tenant-id},
which the formatter tries to interpolate as a variable named tenant-id,
but no values object was provided. Since {tenant-id} is meant to be
literal text (not a dynamic value), we need to escape the curly braces
by wrapping them in '...' quotes per ICU syntax.