Increase wait time for save modal disappearance by using waitForSaveModalToClose (#278473)
## Summary

This is a similar fix as this PR:
https://github.com/elastic/kibana/pull/278306

Some of our tests failed because the save modal was taking more time to
disappear. This PR changed the custom wait for the modal disappears with
custom timeout with the equivalent common utility called:
`waitForSaveModalToClose`.

Related error:
```
Error: timed out waiting for Save modal to disappear
    at onFailure (retry_for_truthy.ts:40:13)
```

<img width="1280" height="1057" alt="image"
src="https://github.com/user-attachments/assets/48ea78b5-9c58-4a7c-9603-1711b7514e91"
/>