[Observability:Onboarding] Dismiss AI modal popup if it is present so ensemble tests can continue (#263776)
## Summary
This PR updates ensemble test flows to include a check for a new AI
modal popup that is present in Kibana. This broke certain ensemble tests
as the popup would occur and click events to sub elements wouldn't be
registered. The ensemble now checks for presence of the modal and if it
is present, the modal will be dismissed so the tests can continue.

## Error context
# Error details

```
Test timeout of 400000ms exceeded.

Error: locator.click: Test timeout of 400000ms exceeded.
Call log:
  - waiting for getByTestId('observabilityOnboardingUseCaseCard-host').getByRole('radio')
    - locator resolved to <input value="" type="radio" name="onboardingCategory:r19:" id="onboardingCategory:r19:_host" class="euiRadio__input css-a6hcpm-euiRadio__input"/>
  - attempting click action
    2 × waiting for element to be visible, enabled and stable
      - element is visible, enabled and stable
      - scrolling into view if needed
      - done scrolling
      - <div data-euiportal="true" data-relative-to-header="above" class="euiOverlayMask css-cjuudi-euiOverlayMask-aboveHeader">…</div> intercepts pointer events
    - retrying click action
    - waiting 20ms
    2 × waiting for element to be visible, enabled and stable
      - element is visible, enabled and stable
      - scrolling into view if needed
      - done scrolling
      - <div data-euiportal="true" data-relative-to-header="above" class="euiOverlayMask css-cjuudi-euiOverlayMask-aboveHeader">…</div> intercepts pointer events
    - retrying click action
      - waiting 100ms
    762 × waiting for element to be visible, enabled and stable
        - element is visible, enabled and stable
        - scrolling into view if needed
        - done scrolling
        - <div data-euiportal="true" data-relative-to-header="above" class="euiOverlayMask css-cjuudi-euiOverlayMask-aboveHeader">…</div> intercepts pointer events
      - retrying click action
        - waiting 500ms
```

## Testing 
Test locally following [this
README](https://github.com/elastic/kibana/blob/main/x-pack/solutions/observability/plugins/observability_onboarding/e2e/playwright/README.md),
you should see the tests dismiss the modal and tests continue as normal.
The modal will only show up once so you should only see one test occur
with the popup.

## Callouts
The modal is only one reason for our current ensemble test failures, I'm
still investigating the tests that are failing for other reasons